
GET http://localhost:5007

###

GET http://localhost:5007/api/categories

###

POST http://localhost:5007/api/categories
Content-Type: application/json

{
    "name": "sports",
    "description": "this category contains all the electronic products"
    //"name": "home appliances",
    //"description": "this category contains all the home appliances products"
}

###

DELETE http://localhost:5007/api/categories/8773844b-8fd0-4aba-a3d5-83b99d757838

###

PUT http://localhost:5007/api/categories/bce29982-d1d8-41a5-9c79-eea848a55989
Content-Type: application/json

{
    "name": "",
    "description": "hi upgraded "
}